import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  async redirects() {
    return [
      // Legacy static social image path, referenced by old shares and
      // podcast directories. The image is now generated by opengraph-image.tsx.
      { source: "/og-image.png", destination: "/opengraph-image", permanent: true },
    ];
  },
  images: {
    remotePatterns: [
      {
        protocol: "https",
        hostname: "images.unsplash.com",
      },
    ],
  },
};

export default nextConfig;
